### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by gabe2004** [intel/video-analytics-serving#10]
Do we have plans to add support for publishing inference results over MQTT?

**Comment by nnshah2** [comment]
MQTT, Kafka, and file publishing are supported for inference results through the gvametapublisher element. This is supported currently only for GStreamer based pipelines.  Please let us know if you have any issues in enabling it.

**Comment by nnshah1** [comment]
MQTT, Kafka, and file publishing are supported for inference results through the gvametapublisher element. This is supported currently only for GStreamer based pipelines. Please let us know if you have any issues in enabling it.

**Comment by gabe2004** [comment]
Thanks

**Comment by lightlu** [comment]
Is there an pipeline.json example to demostrate publishing inference results over MQTT?

**Comment by tobiasmo1** [comment]
Hi @lightlu,

The closest functional example that uses MQTT is found as part of the [EdgeX sample](https://github.com/intel/video-analytics-serving/blob/master/samples/edgex_bridge/README.md).

A person may also directly run any pipelines that include the `gvametapublish` element (such as [./pipelines/gstreamer/object_detection/person_vehicle_bike/pipeline.json](https://github.com/intel/video-analytics-serving/blob/master/pipelines/gstreamer/object_detection/person_vehicle_bike/pipeline.json#L5)) and provide parameters to this "destination".

Example:
1. Install mosquitto_sub and mosquitto_pub clients for testing on host
   ```$ sudo apt-get update && sudo apt-get install -y mosquitto-clients```

2. Run VA Serving.
   ```$  ./docker/run.sh --network host```

3. Launch your mqtt broker:
   ```$  docker run -d --network host --rm --name vaserving_mqtt -p 1883:1883 -p 9001:9001 eclipse-mosquitto```

4. Subscribe to topics that we'll publish inference results on.
   ```$  mosquitto_sub -h localhost -t vaserving/#```

5. Launch the pipeline, providing parameters to gvametapublish destination:
   ```
   $  curl localhost:8080/pipelines/object_detection/person_vehicle_bike -X POST -H \
   'Content-Type: application/json' -d \
   '{
     "source": {
       "uri": "https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4?raw=true",
       "type": "uri"
     },
     "destination": {
       "metadata": {
         "type": "mqtt",
         "host": "127.0.0.1",
         "topic": "vaserving/person_vehicle_bike"
       }
     },
     "parameters": {
       "detection-device": "CPU"
     }
   }'
   ```

**Comment by nnshah1** [comment]
@lightlu As @tobiasmo1 mentioned, all of the reference pipelines (object_detection, object_classification, object_tracking) support metadata publishing to MQTT based on the destination field in the request.

**Comment by lightlu** [comment]
@tobiasmo1  Thank you!! Your response help me a lot.

**Comment by lightlu** [comment]
> 5\. b. Using curl

I try to use curl to launch pipeline with rtsp enabled, but VLC failed to connect rtsp://localhost:8554/vaserving although POST json with "frame": { "type": "rtsp", "path": "vaserving" }. I did it successfully by using VA client command with "--rtsp-path vaserving" on the same environment. Welcome any comment & thank you in advance.

**Comment by nnshah1** [comment]
@lightlu Can you share the full curl command?

**Comment by lightlu** [comment]
@nnshah1 As following, Thank you
`$ curl localhost:8080/pipelines/object_detection/person_vehicle_bike -X POST -H 'Content-Type: application/json' -d \
'{
  "source": {
    "uri": "rtsp://admin:admin@172.22.24.214/multimedia/video1",
    "type": "uri"
  },
  "destination": {
    "metadata": {
      "type": "mqtt",
      "host": "172.22.24.183",
      "topic": "AnalyticsData"
    }
  },
  "frame": {
      "type": "rtsp",
      "path": "vaserving"
  },
  "parameters": {
    "detection-device": "CPU"
  }
}'
`

**Comment by nnshah1** [comment]
It looks like you have an typo in the json request. The frame clause is outside the destination. Does this throw an error - or completes sucessfully?

@whbruce if this completes successfully - we should consider closing our schema to avoid this kind of issue.

```
curl localhost:8080/pipelines/object_detection/person_vehicle_bike -X POST -H 'Content-Type: application/json' -d \ '{ "source": { "uri": "rtsp://admin:admin@172.22.24.214/multimedia/video1", "type": "uri" }, "destination": { "metadata": { "type": "mqtt", "host": "172.22.24.183", "topic": "AnalyticsData" }, "frame": { "type": "rtsp", "path": "vaserving" }}, "parameters": { "detection-device": "CPU" } }'
```

```
{
  "source": {
    "uri": "rtsp://admin:admin@172.22.24.214/multimedia/video1",
    "type": "uri"
  },
  "destination": {
    "metadata": {
      "type": "mqtt",
      "host": "172.22.24.183",
      "topic": "AnalyticsData"
    },
    "frame": {
      "type": "rtsp",
      "path": "vaserving"
    }
  },
  "parameters": {
    "detection-device": "CPU"
  }
}
```

**Comment by lightlu** [comment]
@nnshah1 it completes successfully and mqtt broker receive inference meta json data without problem. However I can not find the right RTSP URL to play video streaming by VLC.

**Comment by lightlu** [comment]
@nnshah1  Your updated json request works! Thank you very much.

**Comment by whbruce** [comment]
@G2020sudo use vaclient's `--show-request` option to help debug requests.

```
$ ./vaclient/vaclient.sh start object_detection/person_vehicle_bike \
 https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4?raw=true \
 --destination type mqtt \
 --destination host 127.0.0.1 \
 --destination topic vaserving/person_vehicle_bike \
-- rtsp-path vaserving \
 --show-request
<snip>
POST http://localhost:8080/pipelines/object_detection/person_vehicle_bike
Body:{'source': {'uri': 'https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4?raw=true', 'type': 'uri'}, 'destination': {'metadata': {'type': 'mqtt', 'path': '/tmp/results.jsonl', 'format': 'json-lines', 'host': '127.0.0.1', 'topic': 'vaserving/person_vehicle_bike'}, 'frame': {'type': 'rtsp', 'path': 'vaserving'}}}
```
Pretty printed payload looks like this
```
{
	'source': {
		'uri': 'https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4?raw=true',
		'type': 'uri'
	},
	'destination': {
		'metadata': {
			'type': 'mqtt',
			'path': '/tmp/results.jsonl',
			'format': 'json-lines',
			'host': '127.0.0.1',
			'topic': 'vaserving/person_vehicle_bike'
		},
		'frame': {
			'type': 'rtsp',
			'path': 'vaserving'
		}
	}
}
```
