### ISSUE TITLE
build.sh not working out of the box. 

### ISSUE THREAD

**Issue by synchronizing** [intel/video-analytics-serving#15]
Will be investigating this further, but as of now, the instructions given in the `README.md` and `samples/README.md` do not seem to work out-of-the-box:

##### [`README.md`](https://github.com/intel/video-analytics-serving/blob/master/README.md)
> ### Building
> 
> To get started, build the service as a standalone component execute the following command
> 
> ```bash
> ./docker/build.sh
> ```

##### [`samples/README.md`](https://github.com/intel/video-analytics-serving/blob/master/samples/README.md)
>   2. Build the service container with sample pipelines:
>      ```
>      ~/video-analytics-serving$ ./docker/build.sh
>      ```

When running `build.sh` the following error is thrown:

```shell 
./docker/build.sh: line 165: ${MODELS^^}: bad substitution
```

I'm assuming necessary flags aren't being set, but in such case, I believe that the README's must be updated. Will update this thread further into the night after some code-reading.

**Comment by nnshah2** [comment]
Thanks for reporting this. Can you let us know what OS / platform you are running on? Definitely designed to run out of the box without any parameters. There might be a dependency on shell version.

**Comment by synchronizing** [comment]
> Thanks for reporting this. Can you let us know what OS / platform you are running on? Definitely designed to run out of the box without any parameters. There might be a dependency on shell version.

Hey @nnshah2. Running on host machine with the following:

```
macOS Catalina 10.15.5
zsh 5.8 (x86_64-apple-darwin19.3.0)
Docker version 19.03.8, build afacb8b
```

**Comment by nnshah1** [comment]
Thanks for reporting this. Can you let us know what OS / platform you are running on? Definitely designed to run out of the box without any parameters. There might be a dependency on shell version. Ah! we have only tested on Ubuntu / bash to date - and probably the build script is incompatible for zsh.

**Comment by nnshah1** [comment]
Is it possible to use bash - otherwise we can post the resulting docker command that you would get by default. I can take a look at zsh to see how we could make it work across shells but don't know how easy that will be

**Comment by synchronizing** [comment]
> Is it possible to use bash - otherwise we can post the resulting docker command that you would get by default. I can take a look at zsh to see how we could make it work across shells but don't know how easy that will be

Using:

```
bash docker/build.sh
```

or 

```
sh docker/build.sh
```

The following is outputted:

```
docker/build.sh: line 165: ${MODELS^^}: bad substitution

Building Video Analytics Serving Image: ''

   Base: ''
   Build Context: '/Users/felipefaria/Desktop/video-analytics-serving'
   Dockerfile: '/Users/felipefaria/Desktop/video-analytics-serving/docker/Dockerfile'
   Build Options: '--network=host'
   Build Arguments: ' --build-arg BASE=  --build-arg FRAMEWORK= --build-arg MODELS_PATH=models --build-arg MODELS_COMMAND=copy_models --build-arg PIPELINES_COMMAND=do_not_copy_pipelines --build-arg FINAL_STAGE=video-analytics-serving-service '
   Models: 'models'
   Pipelines: ''
   Framework: ''
   Target: 'deploy'
   Create Service: 'TRUE'

+ docker build -f /Users/felipefaria/Desktop/video-analytics-serving/docker/Dockerfile --network=host --build-arg BASE= --build-arg FRAMEWORK= --build-arg MODELS_PATH=models --build-arg MODELS_COMMAND=copy_models --build-arg PIPELINES_COMMAND=do_not_copy_pipelines --build-arg FINAL_STAGE=video-analytics-serving-service -t --target deploy /Users/felipefaria/Desktop/video-analytics-serving
invalid argument "--target" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```

**Comment by synchronizing** [comment]
Modifying

https://github.com/intel/video-analytics-serving/blob/59fdcba3e7b631f391cf5654b30f78d56585411b/docker/build.sh#L1

to 

```
!/bin/bash
```

Outputs the same as the above.

**Comment by nnshah1** [comment]
for some reason many of the variables aren't getting set

**Comment by nnshah1** [comment]
```
docker build https://github.com/opencv/gst-video-analytics.git#v1.0.0 -f docker/Dockerfile --network=host --build-arg no_proxy --build-arg https_proxy --b\
        uild-arg http_proxy --build-arg ENABLE_PAHO_INSTALLATION=true --build-arg ENABLE_RDKAFKA_INSTALLATION=true -t video-analytics-serving-gstreamer-base
```
```
docker build -f /home/nnshah1/projects/video-analytics-serving-refactor/video-analytics-serving/docker/Dockerfile --network=host --build-arg no_proxy --bu\
        ild-arg https_proxy --build-arg http_proxy --build-arg BASE=video-analytics-serving-gstreamer-base --build-arg FRAMEWORK=gstreamer --build-arg MODELS_PATH\
        =models --build-arg MODELS_COMMAND=copy_models --build-arg PIPELINES_PATH=pipelines/gstreamer --build-arg PIPELINES_COMMAND=copy_pipelines --build-arg FIN\
        AL_STAGE=video-analytics-serving-service -t video-analytics-serving-gstreamer --target deploy /home/nnshah1/projects/video-analytics-serving-refactor/vide\
        o-analytics-serving
```

**Comment by nnshah1** [comment]
these are the commands you should get out of the box for the build

**Comment by synchronizing** [comment]
Thank you for the help -- let me try some changes to my `bash` setup. OSX comes equipped with `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`, which is dated back to 2006 (likely the issue). I'll be back with some updates + a solution if I find one.

**Comment by nnshah1** [comment]
We will double check the shell requirements and try to find a way to make it portable - in the mean time let us know if those commands work - thanks!

**Comment by synchronizing** [comment]
Found a solution for OSX. 

1. Install latest version of `bash` via [`brew`](https://brew.sh)

```
brew install bash
``

2. Run with new version: 

```
  λ which -a bash
/usr/local/bin/bash
/bin/bash
```

```
/usr/local/bin/bash docker/build.sh
```

Docker is currently doing its thing (downloading + setting up). Will raise new issue if something comes up! @nnshah1 thank you for the help.

**Comment by synchronizing** [comment]
Opened new pull request with small instructions on `README.md` to specify building on OSX via #16. Thank you again @nnshah1.

**Comment by nnshah1** [comment]
@synchronizing Thanks for the pull request! Let us know how you're testing / experience goes. We're not quite set up for accepting pull requests directly but we are working on a documentation update focused on the build & run scripts so we will be sure to include this.

**Comment by synchronizing** [comment]
> @synchronizing Thanks for the pull request! Let us know how you're testing / experience goes. We're not quite set up for accepting pull requests directly but we are working on a documentation update focused on the build & run scripts so we will be sure to include this.

Sounds like a plan! Thanks again. 

Wondering if there is any documentation on adding another model into the system. Currently trying to add [`text-detection-004`](https://docs.openvinotoolkit.org/latest/_models_intel_text_detection_0004_description_text_detection_0004.html) right now, but having some pipeline issues. If you have any resources you could point me to, that would be appreciated. Thank you again for all.

**Comment by nnshah1** [comment]
You should be able to increase the log_level to DEBUG to get more info on the exact error. Most probably in this case there is a typo in the pipeline. 

We are working on improving the documentation, but we can help you through. The basics are to add a directory under models with the structure: model_name/version/FP32/*.bin, *.xml. Once the model is there you can refer to it in a pipeline by: models[model_name][version][network] and VA Serving will fill in the full path at runtime.

The challenge with this specific model is that it's post-processing is not currently handled directly by DLStreamer and you will have to write some custom processing code to convert the tensor output into a bounding box. The simplest approach would be to use the gvapython element and implement the post processing in python. (Section 3 here)

https://github.com/opencv/gst-video-analytics/wiki/Custom-Processing  

The post processing for this model can be found here: 

https://github.com/opencv/open_model_zoo/blob/master/demos/text_detection_demo/src/text_detection.cpp

Many models (ssd, tiny lolo, mobilenet-v2 classification) work out of the box - but unfortunately not this one (yet). If you'd like to see this feature please add a request on the DLStreamer repo. 

https://github.com/opencv/gst-video-analytics

If you decide to go the custom processing route - let us know if you run into any issues

**Comment by synchronizing** [comment]
Awesome information. I'll be sure to look through it all -- as of right now, the intention is to create a seperate model all together, but I was hoping to give the framework a try with `text-detection-004`. If this isn't working out-of-the-box, then I believe time is better spent on just integrating the custom model to begin with! I'll be working on this in the next few days, and let you guys know of any issue.

Again, thank you for all the help and support.

**Comment by nnshah1** [comment]
As an example of using gvapython with VA Serving to do custom processing, you can take a look at:
(This show how to insert the gvapython into the pipeline)

https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/analytics/crowd/Xeon/gst/pipeline/2/pipeline.json

This shows a simple python function to do custom processing.

https://github.com/OpenVisualCloud/Smart-City Sample/tree/master/analytics/crowd/custom_transforms
