### ISSUE TITLE
time stamp issue

### ISSUE THREAD

**Issue by xwu2git** [intel/video-analytics-serving#21]
vaserving/gstreamer_pipeline.py, line 274:
self._stream_base = times["segment.time"]

This line should be self._stream_base=times["stream_time"]
times["segment.time"] and times["stream_time"] are in different time units that it does not make sense to do subtraction as in line 285:

 adjusted_time = self._real_base + \
            (times["stream_time"] - self._stream_base)

**Comment by nnshah1** [comment]
Thanks @xwu2git - we will look into the semantics and confirm for next release.

**Comment by akwrobel** [comment]
Closed due to no response
