### ISSUE TITLE
FFmpeg pipeline failed on 0.3-alpha

### ISSUE THREAD

**Issue by QuPengfei** [intel/video-analytics-serving#23]
ffmpeg failed on the 0.3-alpha. it worked well when rolling back to 0.3-preview.

**Comment by nnshah1** [comment]
@QuPengfei Can you provide more details on the specific pipeline? If possible please include a link to the pipeline.json.

**Comment by QuPengfei** [comment]
the issue can be reproduced with the following pipeline. i did not try the face and emotion use case.  and i think face/emotion have the similar issue. also the same issue in the VCACA.

https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/ad-insertion/analytics/Xeon/ffmpeg/pipelines/object_detection/1/pipeline.json

**Comment by whbruce** [comment]
I tested with the 0.4 release and pipeline seemed to work
```bash
$ docker/build.sh --framework ffmpeg
$ docker/run.sh --framework ffmpeg --pipelines /path/to/Ad-Insertion-Sample/adinsertion/analytics/Xeon/ffmpeg/pipelines
```
Then
``` bash
$ samples/sample.py
Launching with options:
Namespace(destination='/tmp/results.txt', pipeline='object_detection', repeat=1, source='https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true', verbose=True, version='1')
Starting Pipeline: http://localhost:8080/pipelines/object_detection/1
Pipeline Status:

{
    "avg_fps": 0,
    "elapsed_time": 0.0043637752532958984,
    "id": 1,
    "start_time": 1610067108.4090872,
    "state": "QUEUED"
}
Pipeline Status:

{
    "avg_fps": 0,
    "elapsed_time": 0.5147325992584229,
    "id": 1,
    "start_time": 1610067108.4090872,
    "state": "RUNNING"
}
Pipeline Status:

{
    "avg_fps": 0,
    "elapsed_time": 1.0265381336212158,
    "id": 1,
    "start_time": 1610067108.4090872,
    "state": "RUNNING"
}
Pipeline Status:

{
    "avg_fps": 0,
    "elapsed_time": 1.5306789875030518,
    "id": 1,
    "start_time": 1610067108.4090872,
    "state": "RUNNING"
}
```
Inference results looked good.

Can you retry?

**Comment by akwrobel** [comment]
@QuPengfei We have had no update on this issue, kindly update this issue with the requested information or this issue will be closed.

**Comment by akwrobel** [comment]
This has not been an issue since the 0.4.0 release, current release is 0.6.1.  No action has been taken in the last 2+ weeks to confirm if issues are still seen.
