### ISSUE TITLE
docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

### ISSUE THREAD

**Issue by yangyyt** [intel/video-analytics-serving#34]
When I execute this command ：/usr/local/bin/bash ./docker/run.sh -v /tmp:/tmp ，the terminal displays
docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

How can I solve this problem？I'm not good at docker.

**Comment by nnshah1** [comment]
Please comment out the follow line in the run.sh script - this indicates that the graphics HW in your setup is not available ( we will look into auto detecting this scenario):

https://github.com/intel/video-analytics-serving/blob/e735a1728fb4f19ddce51b5e6d42ef2bf4456ac7/docker/run.sh#L241

**Comment by nnshah1** [comment]
@yangyyt Did this solve your issue?

**Comment by yangyyt** [comment]
> Please comment out the follow line in the run.sh script - this indicates that the graphics HW in your setup is not available ( we will look into auto detecting this scenario):
> 
> https://github.com/intel/video-analytics-serving/blob/e735a1728fb4f19ddce51b5e6d42ef2bf4456ac7/docker/run.sh#L241


> @yangyyt Did this solve your issue?
yes ,it can run now ,but it cannot get me a result .
![image](https://user-images.githubusercontent.com/26132147/92679326-b3f4ea00-f35a-11ea-80e5-491b19e38df2.png)

**Comment by nnshah1** [comment]
@yangyyt can you share the exact command line - it looks as if the output destination is not writeable

**Comment by yangyyt** [comment]
> @yangyyt can you share the exact command line - it looks as if the output destination is not writeable

curl localhost:8080/pipelines/audio_detection/1 -X POST -H \
'Content-Type: application/json' -d \
'{ 
  "source": {
    "uri": "https://github.com/opencv/gst-video-analytics/blob/preview/audio-detect/samples/gst_launch/audio_detect/how_are_you_doing.wav?raw=true",
    "type": "uri"
  },
  "destination": {
    "type": "file",
    "path": "~/Desktop/20200202/下半年/intel/video-analytics-serving/tmp/results_audio_events.txt",
    "format": "json-lines"
  }
}'

**Comment by yangyyt** [comment]
> @yangyyt can you share the exact command line - it looks as if the output destination is not writeable

I'm try to use absolute address for path(/Users/yuntingyang/Desktop/20200202/下半年/intel/video-analytics-serving/tmp/results_audio_events.txt).so results_audio_events.txt can be got ,but its content is empty. 
![image](https://user-images.githubusercontent.com/26132147/92693043-9e41ed80-f377-11ea-812e-7b1bc0276074.png)

**Comment by yangyyt** [comment]
> > @yangyyt can you share the exact command line - it looks as if the output destination is not writeable
> 
> I'm try to use absolute address for path(/Users/yuntingyang/Desktop/20200202/下半年/intel/video-analytics-serving/tmp/results_audio_events.txt).so results_audio_events.txt can be got ,but its content is empty.
> ![image](https://user-images.githubusercontent.com/26132147/92693043-9e41ed80-f377-11ea-812e-7b1bc0276074.png)

just the network is not better.

**Comment by nnshah1** [comment]
The results file path will need to be accessible in the docker container as well as in the host. When you start the container please pass in an appropriate volume mount, as an example (please note it looks as if you are running under windows so the first path may need changing based on how you've set up file mountint.

`./docker/run.sh -v /mnt/c/Users/yuntingyang:/tmp/output`

Then in your curl request, make the path relative to the docker path:

```
"destination": {
"type": "file",
"path": "/tmp/output/results_audio_events.txt",
"format": "json-lines"
}
```

This error:

```
A network error occurred, or the server closed
```

Indicates that the pipeline can't access the sample content. Can you ensure you have proxy variables set correctly - alternatively you can use the pre-download content in the samples folder:
```
'{
"source": {
"uri": "file:///home/video-analytics-serving/samples/how_are_you_doing.wav",
"type": "uri"
},
```

**Comment by yangyyt** [comment]
> The results file path will need to be accessible in the docker container as well as in the host. When you start the container please pass in an appropriate volume mount, as an example (please note it looks as if you are running under windows so the first path may need changing based on how you've set up file mountint.
> 
> `./docker/run.sh -v /mnt/c/Users/yuntingyang:/tmp/output`
> 
> Then in your curl request, make the path relative to the docker path:
> 
> ```
> "destination": {
> "type": "file",
> "path": "/tmp/output/results_audio_events.txt",
> "format": "json-lines"
> }
> ```
> 
> This error:
> 
> ```
> A network error occurred, or the server closed
> ```
> 
> Indicates that the pipeline can't access the sample content. Can you ensure you have proxy variables set correctly - alternatively you can use the pre-download content in the samples folder:
> 
> ```
> '{
> "source": {
> "uri": "file:///home/video-analytics-serving/samples/how_are_you_doing.wav",
> "type": "uri"
> },
> ```

The program runs on a MAC, but I got it. just I didn't set the proxy variable. Thank you very much for your answer

**Comment by nnshah1** [comment]
@yangyyt great news! Will close the issue. Let us know any feedback you have on the audio event detection sample and va serving in general.
