### ISSUE TITLE
Opencv contrib

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#36]
Please tell me the changes I need to make docker image with opencv contrib library

Thank U

**Comment by whbruce** [comment]
I think OpenCV is built as part of [DLDT](https://github.com/openvinotoolkit/openvino), which is built by the DL Streamer base image, see [DockerFile#L569](https://github.com/openvinotoolkit/dlstreamer_gst/blob/preview/audio-detect/docker/Dockerfile#L569). Look into DLDT cmake build options and see if you can add OpenCV contrib.

**Comment by vtimofeev01** [comment]
I am not so advanced? please help where to look

**Comment by brmarkus** [comment]
I needed OpenCV-contrib as well - but did it manually and in addition...
First find out the version of OpenCV used. In my case it was OpenCV in version 4.2.0.

Then I cloned OpenCV and OpenCV-Contrib source code with the same version 4.2.0:

Parent folder, e.g. under "/localdisk/":

```
mkdir opencv-contrib
cd opencv-contrib
```

Clone OpenCV:
```
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 4.2.0-openvino
cd ..
```

Clone OpenCV-Contrib:
```
git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout 4.2.0
cd ..
```

Build OpenCV by telling OpenCV to also use OpenCV-Contrib from another folder (and to install it to "/usr/local/contrib/"):
```
cd opencv
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/contrib/ -DOPENCV_EXTRA_MODULES_PATH=/localdisk/opencv-contrib/opencv_contrib/modules/ ../
make -j 20
sudo make install
```

Depending what you would need from OpenCV-Contrib you could add the parameter "-DBUILD_LIST=" with a lost of modules to the cmake command.

**Comment by vtimofeev01** [comment]
Thank U

**Comment by nnshah1** [comment]
@brmarkus Can you recommend where you would add this to the dockerfile? Can this be done in the last layer (after all other dependencies from openvino/data_dev containers for example) - or does it need to be done before that?

If this is a common need / pattern we can add it to our documentation as part of customizing the build process.

**Comment by brmarkus** [comment]
OpenVINO comes with a pre-built installation of OpenCV already, but without any module from opencv_contrib - as far as I can see. What I described above will add another opencv plus opencv_contrib - but in the same version. With some Dockerfile magic this could be cleaned up for the final layer, so that only the corresponding opencv_contrib module's binaries stay, plus making sure they could be found (ldconfig, library-search-path).

**Comment by nnshah1** [comment]
@brmarkus perfect, thanks! Will try to see how to document the process.

**Comment by vtimofeev01** [comment]
> OpenVINO comes with a pre-built installation of OpenCV already, but without any module from opencv_contrib - as far as I can see. What I described above will add another opencv plus opencv_contrib - but in the same version. With some Dockerfile magic this could be cleaned up for the final layer, so that only the corresponding opencv_contrib module's binaries stay, plus making sure they could be found (ldconfig, library-search-path).

How to add it in the final layer of Dockerfile
