### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#39]
I am trying to connect local mqtt server via metapublishing, but messages are not comming
if I use "file" option i get normal output
if I try to map 1883 port by docker starting i get 
`docker: Error response from daemon: driver failed programming external connectivity on endpoint vaserving (c8500fbaa086ec460d88dcda03bf3e2d18a5fb81b1e4fa649a7aec756766addb): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use.`

**Comment by nnshah1** [comment]
It looks like you are trying to start a mqtt server / bind an mqtt server within the vaserving container?

Typically we start the mqtt server in a seperate container, and expose its port 1883. The ports of the vaserving container should not require any additional configuration (i.e. as long as it has access to the local network, which generally by default it should have). 

if they are both on the same machine, I would first try starting both with `--network host` flag to docker run, and use the mqtt address "localhost:1883" in your va serving destination.

**Comment by vtimofeev01** [comment]
Tks
