### ISSUE TITLE
pipeline don t reaches cameras

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#43]
I have rebuild docker with ` ./docker/build.sh --framework gstreamer --base openvino/ubuntu18_runtime:2020.4` and I tried
with ` ./docker/build.sh --framework gstreamer --base openvino/ubuntu18_runtime:2021.1`

docker starts with 
```
/home/imt/area_overwatch/grabbing/run.sh -v /tmp:/tmp \
    --name vaserving \
    --network host \
    -e DISPLAY=$DISPLAY \
    -v "$HOME/.Xauthority:/root/.Xauthority:rw" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    --device /dev/dri \
    --models /home/imt/area_overwatch/grabbing/samples/models/intel/ \
    --pipelines /home/imt/area_overwatch/grabbing/pipelines
```
but I don t see cameras from the docker connections get always ERROR
(I tried also without network host with     `-p 554:554 `)
Thank U

**Comment by nnshah1** [comment]
@vtimofeev01 Was this working previously and is not working with the latest release?

What ERROR are you getting and what is the pipeline?

**Comment by vtimofeev01** [comment]
Probably I found the reason
my script stores some data to attached via `-v` folders, but when I try to do it i get access denied
(tried also with `touch 1.txt`)
on my dev pc there are no trouble like this
Thank U

**Comment by nnshah1** [comment]
Ah, yes. When using the `openvino` base image, user 1000 gets mapped to `openvino` and not `vaserving`, thus volume mounted files may be inaccessbile to the `vaserving`.

The correct way to handle it is to pass a `--user` option when launching the container with the `userid` of the user who has access to the mounted volume, or to make the volume world writable / readable (for example using `/tmp`)

**Comment by vtimofeev01** [comment]
TU
all is clear
