### ISSUE TITLE
opencv-contrib-python 

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#48]
i need to use opencv-contrib-python before I used OpenVisulaCloud to use a standard opencv-contrib-python  but now i can t
Thank U

**Comment by nnshah1** [comment]
@vtimofeev01 Is it that the base image change prevents this from happening? You can still use openvisulcloud images as a base - can you provide more details on what has changed?

**Comment by vtimofeev01** [comment]
I tried to use OVC images but i get and I added opencv-contrib into "requirements.service.txt", but it does not help

Collecting opencv-contrib-python (from -r /requirements.service.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/2a/ef/6ed8ef6aca8ea9625d6577381dad57762713fd532ad41541054b01f760b3/opencv-contrib-python-4.4.0.46.tar.gz (148.8MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vizrthja/opencv-contrib-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vizrthja/opencv-contrib-python/
The command '/bin/bash -c pip3 install  --no-cache-dir -r /requirements.service.txt' returned a non-zero code: 1

**Comment by vtimofeev01** [comment]
Please let me know what i do wrong

**Comment by vtimofeev01** [comment]
the issue is to use -headless module
