### ISSUE TITLE
Multiple running pipelines

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#50]
Does I right understand that I can run some pipelines in one VAS-container or not?

**Comment by nnshah2** [comment]
Yes, you can run multiple concurrent pipelines in the same VAS container-

**Comment by nnshah1** [comment]
Yes, you can run multiple concurrent pipelines in one VAS container. The VAS microservice supports multiple pipelines in a single process (though pipelines are logically seperate and independent). do you have a specific issue / use case you are trying to enable?

**Comment by whbruce** [comment]
What more information do you need to close this issue?

**Comment by vtimofeev01** [comment]
Tks. Thats all
