### ISSUE TITLE
ONNX build error while building VAS

### ISSUE THREAD

**Issue by NeethuES-intel** [intel/video-analytics-serving#52]
Unable to build ONNX package while running the build command for VAS using following
VAS_VERSION=v0.3.1-alpha
vas:
	rm -rf video-analytics-serving && \
	git clone https://github.com/intel/video-analytics-serving && \
	cd video-analytics-serving/docker && \
	git checkout ${VAS_VERSION} && \
	./build.sh --framework gstreamer
	cd ../..
	docker build -t video-analytic:paho .

Attached is the error log.
Tried on two different linux machines running ubuntu 18 & 20. Getting the same error.
[error_log.txt](https://github.com/intel/video-analytics-serving/files/5840302/error_log.txt)

**Comment by nnshah2** [comment]
@NeethuES-intel `VAS_VERSION=v0.3.1-alpha` is no longer supported and may have incompatible dependencies. 

Can you try the latest version `VAS_VERSION=v0.4.0-beta' ? 

Please let us know if you have any issues in migration or it is impossible to move to the latest.

**Comment by nnshah1** [comment]
@NeethuES-intel VAS_VERSION=v0.3.1-alpha is no longer supported and may have incompatible dependencies.

Can you try the latest version `VAS_VERSION=v0.4.0-beta' ?

Please let us know if you have any issues in migration or it is impossible to move to the latest.

**Comment by NeethuES-intel** [comment]
Thanks @nnshah1.
I tried building with v0.4.0-beta, but getting the following error now. 
I tried running the build with sudo, but getting the same error. Do you have any pointers ?

Defaulting to user installation because normal site-packages is not writeable
Collecting paho-mqtt
  Downloading paho-mqtt-1.5.1.tar.gz (101 kB)
Using legacy 'setup.py install' for paho-mqtt, since package 'wheel' is not installed.
Installing collected packages: paho-mqtt
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/openvino/.local'
Check the permissions.

WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/bin/python3.6 -m pip install --upgrade pip' command.
The command '/bin/bash -c pip3 install paho-mqtt' returned a non-zero code: 1
make: *** [Makefile:30: vas] Error 1

**Comment by nnshah1** [comment]
We haven't run across this specific issue (yet) - can you let us know the host OS and docker version you are using?

We typically set up our docker environments for non sudo access - so you shouldn't need to build with sudo. 

If your environment is set up for sudo only use of docker - that might be a difference we need to test.

**Comment by NeethuES-intel** [comment]
Host OS - Ubuntu 20.04 LTS
Docker version - 
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by NeethuES-intel** [comment]
Issue is resolved. Mostly the version incompatibility & some bugs in the docker & yaml files.

**Comment by NeethuES-intel** [comment]
Following are the steps followed to get Digital out of home built & running -
1) Change to VAS_VERSION=v0.4.0-beta in Makefile
2) Add following in Dockerfile to resolve paho mqtt install -
USER root
3) build vas -
make vas
4) Commented out portainer stuff from docker-compose-vap.yml
5) Go to https://github.impcloud.net/Digital-Out-of-Home/vas-pipeline-manager/tree/master/pipelines/gstreamer
6) Delete all folder except person_detection/1
7) Only keep pipeline.json, delete other two files - pipeline.json.appsink & pipeline.json.display
8) Edit  https://github.impcloud.net/Digital-Out-of-Home/vas-pipeline-manager/blob/master/pipelines/gstreamer/person_detection/1/pipeline.json
Delete - file-format='json-lines' in line 9
9) Run make run-vap to run the VAS docker containers to load pre-defined pipelines
10) video-analytic docker should be up & running, along with other edgex containers
11) Change directory to vs-driver and execute the command go run main.go to see the output on the console.

**Comment by nnshah1** [comment]
@NeethuES-intel Thanks for the instructions and thanks to @thanajirao for the quick resolution!
