### ISSUE TITLE
Unpredictable delay in receiving mqtt messages

### ISSUE THREAD

**Issue by venkataram9** [intel/video-analytics-serving#54]
Hi Team,
I am using using rtsp as input source and MQTT as destination in the pipeline. The input video file is 30FPS. I am using vlc to simulate the rtsp stream. The delay between frames is calculated. It is around 32 ms. The delay in MQTT messages is unpredictable. The delay in MQTT messages frequently changes from 0-150 ms. Since the frame delay is 32ms, how the delay in MQTT is less than 33 ms. Please help me in understanding this.

The code snippet used for calculation is below:

msg_t1 = 0
def on_message(client, userdata, msg):
  global msg_t1
   message = str(msg.payload.decode("utf-8"))
   message = json. loads(message)
   delay = (time.time() - msg_t1) * 1000
   print("delay in ms = ", delay)
   msg_t1 = time.time()

Thank you
Venkat

**Comment by nnshah1** [comment]
@venkataram9 How are you measuring the delay of the MQTT message?

The timestamp in the JSON message is relative to the presentation time of the frame. This is not absolute or system time but relative to when the frame should be "presented". As RTSP includes buffering - the presentation time of the frame can reach mqtt before it should be "presented". What is your final goal in synchronization?

**Comment by nnshah1** [comment]
@venkataram9, Does that help? Do you need more information / have more details on your requirements?

**Comment by venkataram9** [comment]
Is there a way to get the rtsp timestamp for the inferred image through the mqtt JSON message?
My final goal is to synchronise the video feed and metadata using the code.

**Comment by nnshah1** [comment]
What are the two processes that are receiving the rtsp stream? One is the analytics pipeline, the other is a viewer of some kind? Is it possible to restream the incoming feed from the analytics pipeline? In that way we can synchronize the timestamps easier. 

Overall, recording the stream with a common time stamp as demonstrated is simpler, see:
[https://github.com/intel/video-analytics-serving/tree/master/samples/record_playback] (record_playback)

Recovering the original rtsp timestamp I'm sure is possible - but I haven't put together all the pieces required to do it.  If possible  I would encourage you to record or restream from the sample process / pipeline that does the analytics - in that way you can ensure a common notion of time. 

Synchronizing with an independent pipeline / process is more complex. What are the final requirements?

**Comment by nnshah1** [comment]
In general, to synchronize correctly you'll have to change the clock used in the GStreamer pipeline - 

(this would require changes in (https://github.com/intel/video-analytics-serving/blob/master/vaserving/gstreamer_pipeline.py)) 

Some references I found when attempting this myself:

1. (http://gstreamer-devel.966125.n4.nabble.com/Synchronizing-multiple-RTP-sources-td4672395.html)
2. (https://gstreamer.freedesktop.org/data/events/gstreamer-conference/2015/Sebastian%20Dr%C3%B6ge%20-%20Synchronised%20multi-room%20media%20playback%20and%20distributed%20live%20media%20processing%20and%20mixing%20with%20GStreamer.pdf)


If you get it working - please let us know -

**Comment by venkataram9** [comment]
Could you please brief what should be the changes required in (https://github.com/intel/video-analytics-serving/blob/master/vaserving/gstreamer_pipeline.py)) and in the elements in the pipeline

**Comment by nnshah1** [comment]
@venkataram9 What's the general urgency / priority of your question? Before recommending specific changes we would want to do some analysis to give better guidance as clocks and timing can be complicated.

**Comment by venkataram9** [comment]
We are having short timelines in this implementation. Kindly let us know as soon as possible.

**Comment by whbruce** [comment]
Use the pattern shown in the [record_frames](https://github.com/intel/video-analytics-serving/tree/master/samples/record_frames) samples to match frames to MQTT meta-data results.  Let us know if that helps.
