### ISSUE TITLE
Memory  leaks

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#62]
Hello!

does U have examined memory leaks by using python modules?
I have tried a script with different count of python modules in different combinations, every time i get memory leaks and after some time script stops to run without stopping a pipeline itself. Here I attach a [ picture with statistic](https://drive.google.com/file/d/1YAvXhAxIWlIaettVro-DGb9KfrTm_AtV/view?usp=sharing) Every time that the memory goes down - is the restart.
I used also gc.collect() and multiple del XXXX in python code to escape it but...
in debug mode for gc.collect I see multiple frame, tuple, query etc objects
I have tried many combinations with modules my own or standard
Thank U

**Comment by nnshah1** [comment]
Can you give more details about how and where you are using va serving in this set up? Is va serving growing in memory over time? 

We had done some memory analysis in the past and were able to bound the growth to a small amount for each pipeline - but not a huge continually growth -

**Comment by vtimofeev01** [comment]
As U could see the grows goes continually
Probably something is wrong, but I don t understand what
I run OVC on Intel NUC in docker with GPU
code I use looks like
`import datetime
import json
import logging
import os
import traceback
import gc
import yaml
from gstgva import VideoFrame, Tensor

debug = False
logging_level = logging.DEBUG if debug else logging.INFO
main_logger = logging.getLogger(f'filter_{datetime.datetime.now()}')
main_logger.setLevel(logging_level)
logger_handler = logging.FileHandler(f'{os.environ["FILE_HANDLER_FOLDER"]}/filter_{datetime.datetime.now()}.log')
logger_handler.setLevel(logging_level)
logger_handler.setFormatter(logging.Formatter(f"%(asctime)s %(message)s"))
main_logger.addHandler(logger_handler)
main_logger.info('MODULE READ')


def get_tensor_from_roi_by_model_name(roi, code, value):
    param = roi.meta()._params
    while param:
        t = Tensor(param.contents.data)
        if t[code] == value:
            return t
        param = param.contents.next
    return None


class Filter(object):

    def __init__(self, **kwargs):
        self.i = 0
        self.prefix = 'motion'
        self.prefix_l = len(self.prefix)
        self.f = {}
        self.prefix_cost = 5000
        main_logger.debug(f'[FILTER] from kwargs {kwargs.get("config", "NO CONFIG IN KWARGS")}')
        fn = kwargs.get('config', "/home/openvino/gst/filter_settings.yaml")
        exists = os.path.exists(fn)
        if exists:
            main_logger.info(f'[FILTER] read {fn}')
            self.f.update(yaml.load(open(fn), Loader=yaml.SafeLoader))
            main_logger.debug(f'[Filter] {self.f}')
        else:
            main_logger.debug(f'[FILTER] no yaml config')
        self.c2id = {"multy": 10000, "non-person": 10001, 'wrong': 10002}
        main_logger.info(f'[FILTER SETTINGS] rules={self.f}')
        main_logger.info(f'[FILTER SETTINGS] label_ids={self.c2id}')
        self.counter = 0

    def process_frame(self, frame: VideoFrame) -> bool:
        self.counter += 1
        bbox = None
        roi_type = None
        x, y, w, h = None, None, None, None
        code = None
        main_logger.debug(f'i={self.i} number of rois={len(list(frame.regions()))}')
        try:
            if self.counter % 1000 == 0:
                gc.collect()
            for nn, roi in enumerate(list(frame.regions())):
                roi_type = roi.label()
                rt = roi_type
                from_motion = roi_type[:self.prefix_l] == self.prefix
                new_label = None
                new_label_id = None
                bbox = roi.rect()
                conf = roi.confidence()
                x, y, w, h = bbox.x, bbox.y, bbox.w, bbox.h
                main_logger.debug(f'roi: {nn} x y w h ={x},{y},{w},{h} conf:{conf} type={roi_type} mn={from_motion}')
                if from_motion:
                    new_label = roi_type[self.prefix_l:]
                    rt = new_label
                    new_label_id = roi.label_id() - self.prefix_cost
                    conf = 499
                    main_logger.debug(f'new label must be set to {new_label} id:{new_label_id}')
                if rt not in self.f:
                    main_logger.debug(f'bypass')
                    continue
                for key, value in self.f[rt].items():
                    if key == 'min_width' and w < value:
                        frame.remove_region(roi)
                        new_label = None
                        main_logger.debug(f'roi {roi_type}/{rt} {roi.rect()} removed due width {w} < min:{value}')
                        break
                    elif key == 'min_high' and h < value:
                        main_logger.debug(f'roi {roi_type}/{rt} {roi.rect()} removed due height {h} < min:{value}')
                        frame.remove_region(roi)
                        new_label = None
                        break
                    elif key == 'min_thr' and conf * 1000 < value:
                        main_logger.debug(
                            f'roi {roi_type}/{rt} {roi.rect()} removed due threshold {conf * 1000:0.0f} < min:{value}')
                        frame.remove_region(roi)
                        new_label = None
                    else:
                        t = get_tensor_from_roi_by_model_name(roi, 'attribute_name', key)
                        if t is None:
                            continue
                        t = t.label()
                        if t in self.f[rt][key]:
                            code = self.f[rt][key][t]
                            if code in ('none', 'wrong', 'non-person'):
                                main_logger.debug(f'roi {roi_type}/{rt} {roi.rect()} removed due code={code}')
                                frame.remove_region(roi)
                                new_label = None
                            else:
                                new_label = code
                                new_label_id = new_label_id if from_motion else self.c2id.get(code, code)
                                main_logger.debug(f'roi {roi_type}/{rt} {roi.rect()} set to code:{code} newlabel:{new_label}'
                                             f' id:{new_label_id}')
                if new_label is not None:
                    new_roi = frame.add_region(x=x, y=y, w=w, h=h, label=new_label, confidence=conf)
                    new_roi.detection()['label_id'] = new_label_id
                    main_logger.debug(f'set new roi: lbl:{new_label} id:{new_label_id} conf:{conf} x y w h ={x},{y},{w},{h}')
                    frame.remove_region(roi)

        except:
            main_logger.error(f'Error! {traceback.format_exc()}')
            main_logger.error(f'f={self.f}')
            main_logger.error(f'bbox={bbox}')
            main_logger.error(f'roi_type={roi_type}')
            main_logger.error(f'code={code}')
            main_logger.error(f'x, y, w, h ={x} {y} {w} {h}')
        self.i += 1
        main_logger.debug('filter ends')
        return True
`

**Comment by vtimofeev01** [comment]
I tried with `fakesink`. It works for a long time. I don t see fps, but the code is stable. Graph [here](https://drive.google.com/file/d/1u9Exmo0hPn_lY8twl8pYo4sNGbw_r34_/view?usp=sharing)

**Comment by whbruce** [comment]
Closing issue as it is reported as fixed. We're tracking a smaller leak issue at #70. If you see any more issues please let us know.

Thanks for using VA Serving.
