### ISSUE TITLE
Duplicate MQTT messages with same timestamp

### ISSUE THREAD

**Issue by pubudu-madhawa** [intel/video-analytics-serving#65]
[FrameTimestampIssue.zip](https://github.com/intel/video-analytics-serving/files/6072454/FrameTimestampIssue.zip)
When the attached python code was run, we experienced 3 pairs of messages with the same timestamps. You can see these in the mqtt_logs.text at lines: 13/14, 21/22 and 25/26.
Wondering what is happening here, my understanding is that each MQTT message should come with unique and incremental timestamp. Is this an instance where both messages were generated close to each other so in the time resolution they fall in to the same ticker?

**Comment by whbruce** [comment]
We looked into this issue and identified incorrect timestamps in the media source that rippled through to MQTT. Closing as this is not a VA Serving issue.
