### ISSUE TITLE
vaclient gives misleading error if server not running

### ISSUE THREAD

**Issue by Mushtaq-BGA** [intel/video-analytics-serving#74]
Hi,
I have ubuntu 18.04. I followed the get started doc and ran ./build.sh , i verified the image was pulled successfully.
when i start using vaclient i get below issue, the command issued was "vaclient list-pipelines" "vaclient list-models" but getting below error

**WARNING: Published ports are discarded when using host network mode
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pipelines (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda55d4a490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Got empty response retrieving pipelines**

request help on this to resolve and move forward

**Comment by whbruce** [comment]
Make sure [the REST running is running](https://github.com/intel/video-analytics-serving#running-the-microservice) before you run vaclient. The vaclient error message is not very helpful - we plan to improve this in our next release.

**Comment by whbruce** [comment]
Fixed in v0.6.0-beta
