### ISSUE TITLE
Error while loading model : MobileNet-SSD

### ISSUE THREAD

**Issue by stepin105519** [intel/video-analytics-serving#76]
Hello all,

I tried to load MobileNet-SSD (converted IR Model), in CPU, Model Network: FP32

Open_model_zoo: https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/mobilenet-ssd/model.yml
Caffe model: Direct deployment MobileNetSSD_deploy.caffemodel
Prototxt file: https://raw.githubusercontent.com/chuanqi305/MobileNet-SSD/ba00fc987b3eb0ba87bb99e89bf0298a2fd10765/MobileNetSSD_deploy.prototxt

IR-Convertion script:
python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo_caffe.py --input_shape [1,3,300,300] --input data --mean_values data[127.5,127.5,127.5] --scale_values data[127.5] --reverse_input_channels --output detection_out --input_model MobileNetSSD_deploy.caffemodel --input_proto MobileNetSSD_deploy.prototxt --output_dir ./IR/

VAS error log:
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,595", "message": "========================", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,596", "message": "Options for vaserving.py", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,596", "message": "========================", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,596", "message": "port == 8080", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,596", "message": "framework == gstreamer", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,597", "message": "pipeline_dir == /home/pipelines", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,597", "message": "model_dir == /home/models", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,597", "message": "network_preference == {'CPU': 'FP32'}", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,597", "message": "max_running_pipelines == 1", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,597", "message": "log_level == INFO", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,598", "message": "config_path == /home/vaserving/..", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,598", "message": "ignore_init_errors == False", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,598", "message": "========================", "module": "vaserving"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,599", "message": "==============", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,599", "message": "Loading Models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,599", "message": "==============", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,599", "message": "Loading Models from Path /home/models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "Loading Model: object_detection_2020R2 version: 1 type: IntelDLDT from {'FP32': '/home/models/object_detection_2020R2/1/FP32/MobileNetSSD_deploy.xml', 'model-proc': '/home/models/object_detection_2020R2/1/MobileNetSSD_deploy.json'}", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "========================", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "Completed Loading Models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "========================", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "=================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,601", "message": "Loading Pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:30,602", "message": "=================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:32,547", "message": "Loading Pipelines from Config Path /home/pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,763", "message": "Loading Pipeline: object_detection version: 4 type: GStreamer from /home/pipelines/object_detection/4/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,821", "message": "Loading Pipeline: object_detection version: 2 type: GStreamer from /home/pipelines/object_detection/2/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,845", "message": "Loading Pipeline: object_detection version: 1 type: GStreamer from /home/pipelines/object_detection/1/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,868", "message": "Loading Pipeline: object_detection version: 3 type: GStreamer from /home/pipelines/object_detection/3/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,868", "message": "===========================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,868", "message": "Completed Loading Pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,869", "message": "===========================", "module": "pipeline_manager"}
[INFO...]Pipeline object_detection Version 1 {'type': 'uri', 'uri': 'rtsp://10.0.3.31:17030/live.sdp'} {'type': 'mqtt', 'host': 'traffic_office1_mqtt', 'clientid': 'jFqU5noBrta5x7iJM6E1', 'topic': 'analytics'} {'sensor': 'ilqT5noBrta5x7iJx6Ej', 'location': {'lat': 45.533498, 'lon': -122.933868}, 'algorithm': 'object-detection', 'office': {'lat': 45.539626, 'lon': -122.929569}} {'inference-interval': 6, 'recording_prefix': '/tmp/rec/ilqT5noBrta5x7iJx6Ej'}
{"levelname": "INFO", "asctime": "2021-07-27 11:38:33,869", "message": "Creating Instance of Pipeline object_detection/1", "module": "pipeline_manager"}
PipelineStatus(avg_fps=0, avg_pipeline_latency=None, elapsed_time=6.67572021484375e-05, id=1, start_time=1627366113.894294, state=<State.QUEUED: 1>)
{"levelname": "ERROR", "asctime": "2021-07-27 11:38:34,247", "message": **"Error on Pipeline 1: gst-library-error-quark: base_inference plugin intitialization failed (3): /opt/build/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(137): acquire_inference_instance (): /GstPipeline:pipeline4/GstGvaDetect:detection:\nFailed to load model '/home/models/object_detection_2020R2/1/FP32/MobileNetSSD_deploy.xml'\n\tstoi\n", "module":** "gstreamer_pipeline"}
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07/27
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07/27/1627366114504416725_312637101.mp4
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07/27
on_created: /tmp/rec/ilqT5noBrta5x7iJx6Ej/2021/07/27/1627366114504416725_312637101.mp4
PipelineStatus(avg_fps=0, avg_pipeline_latency=None, elapsed_time=0.353792667388916, id=1, start_time=1627366113.894294, state=<State.ERROR: 4>)
Pipeline object_detection Version 1 Instance 1 Ended with ERROR
Traceback (most recent call last):
  File "/home/detect-object.py", line 32, in connect
    raise Exception("VA exited. This should not happen.")
Exception: VA exited. This should not happen.

Model-proc:
{
  "json_schema_version" : "1.0.0",
  "input_preproc": [
    {
      "layer_name": "data",
      "color_format": "BGR"
    }
  ],
  "output_postproc": [
    {
      "layer_name": "detection_out",
      "labels": ["","person","car"],
      "converter": "DetectionOutput"
    }
  ]
}

Is there any specific framework wiill only work with VAS or any Openvino IR model will work?

It would be much appreciated, if anyone help me?

**Comment by whbruce** [comment]
Use the VA Serving [model download tool](https://github.com/intel/video-analytics-serving/tree/master/tools/model_downloader) to convert the model as part of the build process. The [change object detection model tutorial](https://github.com/intel/video-analytics-serving/blob/master/docs/changing_object_detection_models.md) will show you how to do this, just use [mobilenet-ssd](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-ssd) instead of yolo-v2-tiny-tf. Let us know if that helps.

**Comment by nnshah1** [comment]
@stepin105519 One other detail to keep in mind.

The current open visual cloud sample uses [openvino 2021.2]( https://github.com/OpenVisualCloud/Dockerfiles/blob/5c6fc851c5dd255f697c74189952f61bb369f9fd/Xeon/ubuntu-18.04/analytics/gst/Dockerfile#L314)

To download a compatible model using the latest vaserving release, you can use the following commands and attached list and pipeline.json file:

```
./docker/build.sh --open-model-zoo-version 2021.2 --open-model-zoo-image openvino/ubuntu18_data_dev --force-model-download
```
I tested this by moving the mobilnet-ssd folder to the object detection pipeline folder in Smart-Cities [folder](https://github.com/OpenVisualCloud/Smart-City-Sample/tree/master/analytics/object/Xeon/gst/pipeline/2)

And moving the `models/mobilenet-ssd` from the download into [folder](https://github.com/OpenVisualCloud/Smart-City-Sample/tree/master/analytics/object/models)

[model_list.zip](https://github.com/intel/video-analytics-serving/files/6893163/model_list.zip)

FYI: @whbruce @xwu2git

**Comment by stepin105519** [comment]
Hello @whbruce and @nnshah1,

Thanks, Recently I came to know about OVC compatible OpenVINO version as mentioned by @nnshah1 ,

I'm able to load few models from Open Model Zoo [person-vehicle-bike-detection-2002](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-vehicle-bike-detection-2002) and [person-vehicle-bike-detection-crossroad-1016](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-vehicle-bike-detection-crossroad-1016) in OVC inside [folder](https://github.com/OpenVisualCloud/Smart-City-Sample/tree/master/analytics/object/models/object_detection_2020R2/1) and updating model-proc (.json files) withrespect to the models.

But, Still I couldn't load a Yolo models say [YoloV3] (https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.2/models_bin/3/person-vehicle-bike-detection-crossroad-yolov3-1020/) inside OVC

Model-proc file:
`{
  "json_schema_version": "2.0.0",
  "input_preproc": [],
  "output_postproc": [
    {
      "converter": "RegionYolo",
      "iou_threshold": 0.5,
      "classes": 80,
      "anchors": [
        10.0,
        13.0,
        16.0,
        30.0,
        33.0,
        23.0,
        30.0,
        61.0,
        62.0,
        45.0,
        59.0,
        119.0,
        116.0,
        90.0,
        156.0,
        198.0,
        373.0,
        326.0
      ],
      "masks": [
        6,
        7,
        8,
        3,
        4,
        5,
        0,
        1,
        2
      ],
      "bbox_number_on_cell": 3,
      "cells_number": 13,
      "labels": [
        "person",
        "bicycle",
        "car",
        "motorbike",
        "aeroplane",
        "bus",
        "train",
        "truck",
        "boat",
        "traffic light",
        "fire hydrant",
        "stop sign",
        "parking meter",
        "bench",
        "bird",
        "cat",
        "dog",
        "horse",
        "sheep",
        "cow",
        "elephant",
        "bear",
        "zebra",
        "giraffe",
        "backpack",
        "umbrella",
        "handbag",
        "tie",
        "suitcase",
        "frisbee",
        "skis",
        "snowboard",
        "sports ball",
        "kite",
        "baseball bat",
        "baseball glove",
        "skateboard",
        "surfboard",
        "tennis racket",
        "bottle",
        "wine glass",
        "cup",
        "fork",
        "knife",
        "spoon",
        "bowl",
        "banana",
        "apple",
        "sandwich",
        "orange",
        "broccoli",
        "carrot",
        "hot dog",
        "pizza",
        "donut",
        "cake",
        "chair",
        "sofa",
        "pottedplant",
        "bed",
        "diningtable",
        "toilet",
        "tvmonitor",
        "laptop",
        "mouse",
        "remote",
        "keyboard",
        "cell phone",
        "microwave",
        "oven",
        "toaster",
        "sink",
        "refrigerator",
        "book",
        "clock",
        "vase",
        "scissors",
        "teddy bear",
        "hair drier",
        "toothbrush"
      ]
    }
  ]
}

`
If you could make your commit on loading Yolov3 Model and it's model-proc file will enhance OVC support w.r.t Yolo models

FYI [discussion](https://github.com/openvinotoolkit/dlstreamer_gst/issues/170l)

**Comment by stepin105519** [comment]
Hello @nnshah1 

Just to give an update, I'm able to load yolov3 models in OVC, and execute it. 

By changing the entry points in [yolov3.json]https://download.01.org/opencv/public_models/022020/yolo_v3/yolo_v3_new.jsonl).
I used [yolo-v3-tf](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/yolo-v3-tf)

**Comment by nnshah1** [comment]
@stepin105519 That's great to hear! Sorry it was tricky to get going. Let us know if you have any other issues.
