### ISSUE TITLE
How to use web camera source?

### ISSUE THREAD

**Issue by lightlu** [intel/video-analytics-serving#83]
Web Camera Source section is noted as TBD in customizing_pipeline_requests.md. Is v4l2src source supported now? Thank you.

**Comment by whbruce** [comment]
Webcam support is possible, but needs a few manual steps. We plan to add more integral support for a range of media sources in a future release.
1. In the gstreamer pipelines folder make a copy of the `object_detection/person_vehicle_bike pipeline/pipeline.json` definition file and name it `object_detection/webcam/pipeline.json`
2. Change the template section in `object_detection/webcam/pipeline.json` to the following. The rest of the definition file must be left as is. We replace `uridecodebin` with `v4l2src` and add `videoconvert`.
```
   "template": ["v4l2src name=source ! videoconvert",
                      " ! gvadetect model={models[object_detection][person_vehicle_bike][network]} name=detection",
                      " ! gvametaconvert name=metaconvert add-empty-results=true ! gvametapublish name=destination",
                      " ! appsink name=appsink"
                      ],
```
3. Issue request as follows using curl. You can select different device by setting the `path` value in the `source` field
```
curl localhost:8080/pipelines/object_detection/webcam -X POST -H \
'Content-Type: application/json' -d \
'{
  "source": {
    "type": "device",
    "path": "/dev/video0"
  },
  "destination": {
    "metadata": {
      "type": "file",
      "path": "/tmp/results.jsonl",
      "format": "json-lines"
    }
  }
}'
```
4. vaclient does not support webcams out of the box. You need to change [vaclient.py#L115](https://github.com/intel/video-analytics-serving/blob/master/vaclient/vaclient.py#L115) from
```python
    if hasattr(args, 'uri'):
         request["source"]["uri"] = args.uri
```
to
```python
    if hasattr(args, 'uri'):
        if args.uri.startswith("/dev/video"):
            del request["source"]["uri"]
            request["source"]["type"] = "device"
            request["source"]["path"] = args.uri
        else:
            request["source"]["uri"] = args.uri
```
then run as follows
```
$ ./vaclient/vaclient.sh run object_detection/webcam /dev/video0
```

**Comment by Advantech-EdgeX-API** [comment]
@whbruce Thank you & sorry for late reply
Let me provide patch to use webcam on /dev/video0 for samples/record_frames/ which based on this git commit.
`v0.6.0-beta master origin/master adv2/master adv/master 2534d9b4d8487864bfdccdfcdc746ccf0f5627d7`
[0001-Force-samples-record_frames-to-use-dev-video0-webcam.zip](https://github.com/intel/video-analytics-serving/files/7089984/0001-Force-samples-record_frames-to-use-dev-video0-webcam.zip)

**Comment by lightlu** [comment]
@whbruce Thank you & sorry for late reply
Let me provide patch to use webcam on /dev/video0 for samples/record_frames/ which based on this git commit:
`v0.6.0-beta origin/master 2534d9b4d8487864bfdccdfcdc746ccf0f5627d7`
[0001-Force-samples-record_frames-to-use-dev-video0-webcam.zip](https://github.com/intel/video-analytics-serving/files/7090011/0001-Force-samples-record_frames-to-use-dev-video0-webcam.zip)

**Comment by whbruce** [comment]
@lightlu thanks for contribution. In the short term we have updated our docs. Our next release will contain  a "universal" VA Serving source so that pipelines can take media from anywhere.
