### ISSUE TITLE
got 500 error when sent request via vaclient.sh

### ISSUE THREAD

**Issue by maozhong1** [intel/video-analytics-serving#85]
I successfully launch the by vaservice  ./docker/run.sh -v /tmp:/tmp
however, when I issue:
 **./vaclient/vaclient.sh run object_classification/vehicle_attributes https://github.com/intel-iot-devkit/sample-videos/blob/master/car-detection.mp4?raw=true**
got following error:

_WARNING: Published ports are discarded when using host network mode
Starting pipeline...
Got unsuccessful status code: 500
"Unexpected error"_

any suggestions? thanks

**Comment by whbruce** [comment]
Please share the log from the service and we'll look into it.

**Comment by whbruce** [comment]
Try using the following curl request -  do you get the same response ?
```
$ curl localhost:8080/pipelines/object_classification/vehicle_attributes -X POST -H \
'Content-Type: application/json' -d \
'{
  "source": {
    "uri": "https://github.com/intel-iot-devkit/sample-videos/blob/master/car-detection.mp4?raw=true",
    "type": "uri"
  },
  "destination": {
    "metadata": {
      "type": "file",
      "path": "/tmp/results.jsonl",
      "format": "json-lines"
    }
  }
}'
```

**Comment by maozhong1** [comment]
Thanks bruce. I tested with your command, got following error. I also paste the error msg in server part.

 curl localhost:8080/pipelines/object_classification/vehicle_attributes -X POST -H 'Content-Type: application/json' -d '{
  "source": {
    "uri": "https://github.com/intel-iot-devkit/sample-videos/blob/master/car-detection.mp4?raw=true",
    "type": "uri"
  },
  "destination": {
    "metadata": {
      "type": "file",
      "path": "/tmp/results.jsonl",
      "format": "json-lines"
    }
  }
}'
**"Unexpected error"**

--------------------------Error msg in server part-----------------------------------------------------------
**ERROR:tornado.access:500 POST /pipelines/object_classification/vehicle_attributes (172.18.0.1) 6.06m**s
{"levelname": "INFO", "asctime": "2021-08-20 01:43:05,910", "message": "Creating Instance of Pipeline object_classification/vehicle_attributes", "module": "pipeline_manager"}
{"levelname": "ERROR", "asctime": "2021-08-20 01:43:05,912", "message": "Exception in pipelines_name_version_post 'person_vehicle_bike'", "module": "endpoints"}

**Comment by maozhong1** [comment]
any suggestions？

**Comment by maozhong1** [comment]
Thanks Thanaji Rao's great help.  This issue is due to some DL model is missing when do inference.  It is my fault to comment " $SOURCE_DIR/tools/model_downloader/model_downloader.sh --model-list $MODELS" in build.sh due to proxy issue in my local PC, I can not download some models successfully.
After reset my modification, it works. Thanks!
