### ISSUE TITLE
Docker build fails if no_proxy setting contains spaces

### ISSUE THREAD

**Issue by yogeshmpandey** [intel/video-analytics-serving#88]
Tried to build the image using 

`./docker/build.sh`

But, getting the issue below:-

![image](https://user-images.githubusercontent.com/2559013/132485954-30e774b4-aafc-4ef5-a6c5-c89145b4337b.png)

**Comment by whbruce** [comment]
This is probably due to a space in your NO_PROXY setting. Run the following to track down the problem.
```
$ grep localhost docker/openvino_base_environment.txt
no_proxy=localhost,127.0.0.1
NO_PROXY=127.0.0.1, localhost
```
If you see  space in either of these values (as in NO_PROXY setting), the build will break with the error you reported. Check your environment and docker proxy configuration for such spaces.

**Comment by yogeshmpandey** [comment]
Thanks, I was able to run it after making the changes. However since I am using a VM, I am getting this issue after running the run.sh command, do we have any fixes for this.

![image](https://user-images.githubusercontent.com/2559013/135425286-8e6eee3f-e8b2-470a-9644-2edd44afc462.png)

**Comment by nnshah1** [comment]
@yogeshmpandey What underlying hardware are you using? Based on this similar issue (also running from within a VM) [https://github.com/opencv/opencv/issues/18932](https://github.com/opencv/opencv/issues/18932 ) it looks like you may need to rebuild opencv / openvino with those options disabled. 

I would suggest trying to rebuild the base openvino image using: 
[https://github.com/openvinotoolkit/docker_ci](https://github.com/openvinotoolkit/docker_ci ) and
[https://github.com/openvinotoolkit/docker_ci](https://github.com/openvinotoolkit/docker_ci/blob/master/get-started.md) 

You'll want to select 'data_runtime' as the type.

Once you've build a openvino data_runtime base image for your HW config, you can use that as a base image for VA Serving:

[https://github.com/intel/video-analytics-serving/blob/master/docs/building_video_analytics_serving.md](https://github.com/intel/video-analytics-serving/blob/master/docs/building_video_analytics_serving.md)

[https://github.com/intel/video-analytics-serving/blob/master/docs/build_script_reference.md](https://github.com/intel/video-analytics-serving/blob/master/docs/build_script_reference.md)

Let us know if that works -

**Comment by yogeshmpandey** [comment]
Thanks, a lot. It worked.
