### ISSUE TITLE
Vaclient script not showing new models added

### ISSUE THREAD

**Issue by Mushtaq-BGA** [intel/video-analytics-serving#91]
i have added new models as per the directory structure required by VAS, however when i used vaclient script to list-models it is not showing up.  Is this a known issue ? if not can you help me.

**Comment by nnshah1** [comment]
@Mushtaq-BGA Can you share the directory structure / build command you used? Are you volume mounting the models folder or are rebuilding the container with the models?

**Comment by Mushtaq-BGA** [comment]
@nnshah1  - 
I got it !!
Actually i missed to mount models  "./docker/run.sh -v /tmp:/tmp **--models models**",  . Thanks
