### ISSUE TITLE
Error while running the pipeline

### ISSUE THREAD

**Issue by smitesh-sutaria** [intel/video-analytics-serving#95]
Hello,

When try to run the ./vaclient/vaclient.sh run object_detection/person_vehicle_bike https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4

Get the below error :

WARNING:tornado.access:404 GET /api/v1/deviceinfo//api/v1/deviceinfo/30 (172.17.0.1) 0.89ms
{"levelname": "ERROR", "asctime": "2021-11-24 13:04:11,589", "message": "Error on Pipeline 1: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12): ../gst/playback/gsturidecodebin.c(1024): no_more_pads_full (): /GstPipeline:pipeline9/GstURIDecodeBin:source:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstPipeline:pipeline9/GstURIDecodeBin:source/GstDecodeBin:decodebin0:\nno suitable plugins found:\nMissing decoder: text/html (text/html)\n", "module": "gstreamer_pipeline"}

**Comment by smitesh-sutaria** [comment]
Adding additional logs :

(gst-plugin-scanner:11): GStreamer-WARNING **: 13:11:21.773: Failed to load plugin '/opt/intel/openvino/data_processing/dl_streamer/lib/libgpurenderer.so': libsvml.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:11): GStreamer-WARNING **: 13:11:21.779: Failed to load plugin '/opt/intel/openvino/data_processing/dl_streamer/lib/libvasot_gpu.so': libimf.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:11): GLib-GObject-WARNING **: 13:11:22.060: cannot register existing type 'GstDashDemux'

(gst-plugin-scanner:11): GLib-CRITICAL **: 13:11:22.060: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:11): GStreamer-CRITICAL **: 13:11:22.060: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,207", "message": "Loading Pipelines from Config Path /home/video-analytics-serving/pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,233", "message": "Loading Pipeline: action_recognition version: general type: GStreamer from /home/video-analytics-serving/pipelines/action_recognition/general/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,236", "message": "Loading Pipeline: audio_detection version: environment type: GStreamer from /home/video-analytics-serving/pipelines/audio_detection/environment/pipeline.json", "module": "pipeline_manager"}
{"levelname": "WARNING", "asctime": "2021-11-24 13:11:22,237", "message": "Missing metaconvert element", "module": "gstreamer_pipeline"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,237", "message": "Loading Pipeline: video_decode version: app_dst type: GStreamer from /home/video-analytics-serving/pipelines/video_decode/app_dst/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,241", "message": "Loading Pipeline: object_tracking version: object_line_crossing type: GStreamer from /home/video-analytics-serving/pipelines/object_tracking/object_line_crossing/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,242", "message": "Loading Pipeline: object_tracking version: person_vehicle_bike type: GStreamer from /home/video-analytics-serving/pipelines/object_tracking/person_vehicle_bike/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,242", "message": "Loading Pipeline: object_detection version: object_zone_count type: GStreamer from /home/video-analytics-serving/pipelines/object_detection/object_zone_count/pipeline.json", "module": "pipeline_manager"}
{"levelname": "WARNING", "asctime": "2021-11-24 13:11:22,243", "message": "Missing metaconvert element", "module": "gstreamer_pipeline"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,243", "message": "Loading Pipeline: object_detection version: app_src_dst type: GStreamer from /home/video-analytics-serving/pipelines/object_detection/app_src_dst/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,244", "message": "Loading Pipeline: object_detection version: person_vehicle_bike type: GStreamer from /home/video-analytics-serving/pipelines/object_detection/person_vehicle_bike/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,244", "message": "Loading Pipeline: object_classification version: vehicle_attributes type: GStreamer from /home/video-analytics-serving/pipelines/object_classification/vehicle_attributes/pipeline.json", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,245", "message": "===========================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,245", "message": "Completed Loading Pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,245", "message": "===========================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2021-11-24 13:11:22,335", "message": "Starting Tornado Server on port: 8080", "module": "__main__"}
WARNING:tornado.access:404 GET /api/v1/deviceinfo//api/v1/deviceinfo/30 (172.17.0.1) 4.44ms
WARNING:tornado.access:404 GET /api/v1/deviceinfo//api/v1/deviceinfo/30 (172.17.0.1) 0.92ms
{"levelname": "INFO", "asctime": "2021-11-24 13:11:59,762", "message": "Creating Instance of Pipeline object_detection/person_vehicle_bike", "module": "pipeline_manager"}
{"levelname": "ERROR", "asctime": "2021-11-24 13:12:00,470", "message": "Error on Pipeline 1: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12): ../gst/playback/gsturidecodebin.c(1024): no_more_pads_full (): /GstPipeline:pipeline9/GstURIDecodeBin:source:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstPipeline:pipeline9/GstURIDecodeBin:source/GstDecodeBin:decodebin0:\nno suitable plugins found:\nMissing decoder: text/html (text/html)\n", "module": "gstreamer_pipeline"}

**Comment by vidyasiv** [comment]
Hi Smitesh,

I was able to recreate your issue, it is likely due to not using the raw format of the video. 
Could you try:
```
./vaclient/vaclient.sh run object_detection/person_vehicle_bike https://github.com/intel-iot-devkit/sample-videos/blob/master/person-bicycle-car-detection.mp4?raw=true
```
The [VA Serving README](https://github.com/intel/video-analytics-serving#running-a-pipeline) has the example command with the working URL for person vehicle bike. For other videos, you could get the raw format by going to the webpage of the media and right click on the "View raw"-> Copy link. In the upcoming release, we will have the commands separated out from the output in the README so they're easier to copy and try out.

If you continue to see issues, I would recommend checking proxy settings.

**Comment by akwrobel** [comment]
@smitesh-sutaria We believe this has been resolved with the http update provided above.  Please let us know if this is not the case.
